add multi-threshold alert fields + test
spaceapegames/go-wavefront pull request #25
Opened 2019-06-21 19:43 UTC by ashwin1dd

Closes #24.

- Add additional fields for multi-threshold alerts
- Add unit test

2019-06-21 19:44 UTC, ashwin1dd commented
@louism517 Could I get a review on this?

2019-06-22 08:31 UTC, louism517 requested changes
Looks good, just a couple of small comments.

2019-06-22 08:31 UTC, louism517 commented on alert.go
> +	Targets map[string]string `json:"targets"`
Could we just add a comment here explaining that Targets should be used for Threshold alerts? (The godocs are auto-generated from these comments)

2019-06-22 08:31 UTC, louism517 commented on alert.go
> +	Conditions map[string]string `json:"conditions"`
Sam here, comment.

2019-06-22 12:34 UTC, ashwin1dd commented
done @louism517

2019-06-22 21:20 UTC, ashwin1dd commented
also, do you want me to bump the version? 1.6.0?

2019-06-23 08:43 UTC, louism517 commented
Yes please! Happy to merge after that. Thanks.

2019-06-23 14:44 UTC, ashwin1dd commented
done @louism517, thanks

2019-06-24 09:28 UTC, louism517 commented
@ashwin1dd Sorry, one more thing. Could you just add a simple example of a threshold alert in examples/alert.go ?

2019-06-26 21:24 UTC, ashwin1dd commented
done @louism517. lmk if this looks good. thanks

2019-06-27 10:28 UTC, merged